server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: app
  static_configs:
  - targets:
      - app
    labels:
      job: grafana
      __path__: "/Users/scirlig/Desktop/golang-expenses-rest-api/app.log"
