CREATE TABLE IF NOT EXISTS `expenses`(
    `id` CHAR(36) UNIQUE NOT NULL,
    `price` FLOAT NOT NULL,
    `title` VARCHAR (500) NOT NULL,
    `currency` ENUM('USD', 'EUR', 'GBP', 'MDL') NOT NULL DEFAULT 'USD',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
